In [1]:
print("pytorch")

pytorch


In [2]:
import torch
print(torch.__version__)

2.5.1+cu124


In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.item()

7

In [5]:
scalar.ndim

0

In [6]:
vector = torch.tensor([1,2])

In [10]:
vector.ndim , vector.shape


(1, torch.Size([2]))

In [11]:
mat = torch.tensor([[1,2],[3,4]])

In [12]:
mat.ndim

2

In [16]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim , MATRIX.shape

(2, torch.Size([2, 2]))

In [20]:
tensor = torch.tensor([
    [[1,2],[3,4]],
     [[5,6],[7,8]]
    ])

In [21]:
tensor.ndim
tensor.shape

torch.Size([2, 2, 2])

In [23]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [24]:
TENSOR.ndim , TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [25]:
torch.rand(2,5)

tensor([[0.9135, 0.7844, 0.9171, 0.8671, 0.8422],
        [0.6736, 0.3369, 0.6560, 0.9651, 0.3076]])

In [26]:
torch.rand(3,224,224)

tensor([[[0.3262, 0.4612, 0.9144,  ..., 0.6468, 0.7635, 0.5562],
         [0.8675, 0.9289, 0.8040,  ..., 0.4035, 0.3921, 0.6229],
         [0.4297, 0.1560, 0.6593,  ..., 0.3387, 0.2982, 0.7922],
         ...,
         [0.6344, 0.1185, 0.2012,  ..., 0.3787, 0.6703, 0.4096],
         [0.1974, 0.3519, 0.8256,  ..., 0.4929, 0.9473, 0.3454],
         [0.3133, 0.7200, 0.2032,  ..., 0.4621, 0.0981, 0.8357]],

        [[0.0265, 0.5516, 0.1781,  ..., 0.8940, 0.2693, 0.9015],
         [0.7122, 0.0895, 0.1995,  ..., 0.6814, 0.9709, 0.2497],
         [0.8456, 0.0932, 0.8344,  ..., 0.7355, 0.1717, 0.2257],
         ...,
         [0.6853, 0.0829, 0.6606,  ..., 0.6162, 0.3830, 0.1736],
         [0.0033, 0.8273, 0.6548,  ..., 0.0521, 0.8930, 0.4196],
         [0.9053, 0.4895, 0.6275,  ..., 0.4432, 0.6992, 0.6943]],

        [[0.9002, 0.6193, 0.1261,  ..., 0.4205, 0.5554, 0.2367],
         [0.4222, 0.3836, 0.0368,  ..., 0.9229, 0.4642, 0.9105],
         [0.7859, 0.6546, 0.6254,  ..., 0.9168, 0.7111, 0.

In [ ]:
import torch
import torchvision.transforms as transforms
from PIL import Image

tensor_image = torch.randint(200, 256, (3, 1000, 1000), dtype=torch.uint8)  # RGB image with pixel values

to_pil = transforms.ToPILImage()
image = to_pil(tensor_image)

image.show()

image.save("output_image.png")


In [ ]:
import sys

print("Memory for int:", sys.getsizeof(1))
print("Memory for float:", sys.getsizeof(1.0))


Memory for int: 28
Memory for float: 24


In [29]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [30]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [31]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
example_tensor = torch.tensor([2,3])
example_tensor

tensor([2, 3])

In [28]:
example_tensor.shape, example_tensor.size(), example_tensor.device, example_tensor.dtype

(torch.Size([2]), torch.Size([2]), device(type='cpu'), torch.int64)

In [32]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [33]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

manipulating tensors

In [ ]:
some_tensor1 = torch.tensor([1,2,3])
some_tensor1 +10
some_tensor1 -1

tensor([0, 1, 2])

In [ ]:
some_tensor1 *10 -1

tensor([ 9, 19, 29])

In [ ]:
mul1 = torch.tensor([[1,2],[3,4]])
mul2 = torch.tensor([[1,2],[3,4]])
torch.matmul(mul1, mul1)

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
tensorA = torch.tensor([[1,2,3],[4,5,6]])
tensorA.shape

torch.Size([2, 3])

In [ ]:
tensorB = torch.tensor([[1,2],[3,4],[5,6]])
tensorB.shape

torch.Size([3, 2])

In [ ]:
torch.matmul(tensorA, tensorB)

tensor([[22, 28],
        [49, 64]])

In [ ]:
torch.matmul(tensorA.T, tensorB.T)

tensor([[ 9, 19, 29],
        [12, 26, 40],
        [15, 33, 51]])

In [ ]:
agg_tensor = torch.tensor([1,2,3,4,5])
agg_tensor.max()
torch.min(agg_tensor)

tensor(1)

In [34]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [35]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [36]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [37]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [38]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [39]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [40]:
x[:, 0]

tensor([[1, 2, 3]])

In [41]:
x[0, 0, :]

tensor([1, 2, 3])

In [42]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [43]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
ten = torch.tensor

In [1]:
!nvidia-smi

Tue Mar  4 16:14:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   70C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [6]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])